[build]
command = "echo 'No build step required for static site deployment'"
publish = "public" # Specify your public folder here

[dev]
command = "npm start" # Command to start your development server
port = 8888 # Port number for the development server
